# Generated by Django 4.2.18 on 2025-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_voting_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
